<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="viewport" content="width=device-width, initial-scale=1">


<meta name="date" content="2017-04-29" />

<title>Survey design: power, precision and sample size</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>



<link href="data:text/css;charset=utf-8,body%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Amargin%3A%201em%20auto%3B%0Amax%2Dwidth%3A%20700px%3B%0Aoverflow%3A%20visible%3B%0Apadding%2Dleft%3A%202em%3B%0Apadding%2Dright%3A%202em%3B%0Afont%2Dfamily%3A%20%22Open%20Sans%22%2C%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20Arial%2C%20sans%2Dserif%3B%0Afont%2Dsize%3A%2014px%3B%0Aline%2Dheight%3A%201%2E35%3B%0A%7D%0A%23header%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0A%23TOC%20%7B%0Aclear%3A%20both%3B%0Amargin%3A%200%200%2010px%2010px%3B%0Apadding%3A%204px%3B%0Awidth%3A%20400px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Aborder%2Dradius%3A%205px%3B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Afont%2Dsize%3A%2013px%3B%0Aline%2Dheight%3A%201%2E3%3B%0A%7D%0A%23TOC%20%2Etoctitle%20%7B%0Afont%2Dweight%3A%20bold%3B%0Afont%2Dsize%3A%2015px%3B%0Amargin%2Dleft%3A%205px%3B%0A%7D%0A%23TOC%20ul%20%7B%0Apadding%2Dleft%3A%2040px%3B%0Amargin%2Dleft%3A%20%2D1%2E5em%3B%0Amargin%2Dtop%3A%205px%3B%0Amargin%2Dbottom%3A%205px%3B%0A%7D%0A%23TOC%20ul%20ul%20%7B%0Amargin%2Dleft%3A%20%2D2em%3B%0A%7D%0A%23TOC%20li%20%7B%0Aline%2Dheight%3A%2016px%3B%0A%7D%0Atable%20%7B%0Amargin%3A%201em%20auto%3B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dcolor%3A%20%23DDDDDD%3B%0Aborder%2Dstyle%3A%20outset%3B%0Aborder%2Dcollapse%3A%20collapse%3B%0A%7D%0Atable%20th%20%7B%0Aborder%2Dwidth%3A%202px%3B%0Apadding%3A%205px%3B%0Aborder%2Dstyle%3A%20inset%3B%0A%7D%0Atable%20td%20%7B%0Aborder%2Dwidth%3A%201px%3B%0Aborder%2Dstyle%3A%20inset%3B%0Aline%2Dheight%3A%2018px%3B%0Apadding%3A%205px%205px%3B%0A%7D%0Atable%2C%20table%20th%2C%20table%20td%20%7B%0Aborder%2Dleft%2Dstyle%3A%20none%3B%0Aborder%2Dright%2Dstyle%3A%20none%3B%0A%7D%0Atable%20thead%2C%20table%20tr%2Eeven%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Ap%20%7B%0Amargin%3A%200%2E5em%200%3B%0A%7D%0Ablockquote%20%7B%0Abackground%2Dcolor%3A%20%23f6f6f6%3B%0Apadding%3A%200%2E25em%200%2E75em%3B%0A%7D%0Ahr%20%7B%0Aborder%2Dstyle%3A%20solid%3B%0Aborder%3A%20none%3B%0Aborder%2Dtop%3A%201px%20solid%20%23777%3B%0Amargin%3A%2028px%200%3B%0A%7D%0Adl%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Adl%20dd%20%7B%0Amargin%2Dbottom%3A%2013px%3B%0Amargin%2Dleft%3A%2013px%3B%0A%7D%0Adl%20dt%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Aul%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Aul%20li%20%7B%0Alist%2Dstyle%3A%20circle%20outside%3B%0A%7D%0Aul%20ul%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Apre%2C%20code%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0Acolor%3A%20%23333%3B%0Awhite%2Dspace%3A%20pre%2Dwrap%3B%20%0A%7D%0Apre%20%7B%0Aborder%2Dradius%3A%203px%3B%0Amargin%3A%205px%200px%2010px%200px%3B%0Apadding%3A%2010px%3B%0A%7D%0Apre%3Anot%28%5Bclass%5D%29%20%7B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20Monaco%2C%20%27Courier%20New%27%2C%20monospace%3B%0Afont%2Dsize%3A%2085%25%3B%0A%7D%0Ap%20%3E%20code%2C%20li%20%3E%20code%20%7B%0Apadding%3A%202px%200px%3B%0A%7D%0Adiv%2Efigure%20%7B%0Atext%2Dalign%3A%20center%3B%0A%7D%0Aimg%20%7B%0Abackground%2Dcolor%3A%20%23FFFFFF%3B%0Apadding%3A%202px%3B%0Aborder%3A%201px%20solid%20%23DDDDDD%3B%0Aborder%2Dradius%3A%203px%3B%0Aborder%3A%201px%20solid%20%23CCCCCC%3B%0Amargin%3A%200%205px%3B%0A%7D%0Ah1%20%7B%0Amargin%2Dtop%3A%200%3B%0Afont%2Dsize%3A%2035px%3B%0Aline%2Dheight%3A%2040px%3B%0A%7D%0Ah2%20%7B%0Aborder%2Dbottom%3A%204px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Apadding%2Dbottom%3A%202px%3B%0Afont%2Dsize%3A%20145%25%3B%0A%7D%0Ah3%20%7B%0Aborder%2Dbottom%3A%202px%20solid%20%23f7f7f7%3B%0Apadding%2Dtop%3A%2010px%3B%0Afont%2Dsize%3A%20120%25%3B%0A%7D%0Ah4%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23f7f7f7%3B%0Amargin%2Dleft%3A%208px%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Ah5%2C%20h6%20%7B%0Aborder%2Dbottom%3A%201px%20solid%20%23ccc%3B%0Afont%2Dsize%3A%20105%25%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%230033dd%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%20%7B%0Acolor%3A%20%236666ff%3B%20%7D%0Aa%3Avisited%20%7B%0Acolor%3A%20%23800080%3B%20%7D%0Aa%3Avisited%3Ahover%20%7B%0Acolor%3A%20%23BB00BB%3B%20%7D%0Aa%5Bhref%5E%3D%22http%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0Aa%5Bhref%5E%3D%22https%3A%22%5D%20%7B%0Atext%2Ddecoration%3A%20underline%3B%20%7D%0A%0Acode%20%3E%20span%2Ekw%20%7B%20color%3A%20%23555%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Edt%20%7B%20color%3A%20%23902000%3B%20%7D%20%0Acode%20%3E%20span%2Edv%20%7B%20color%3A%20%2340a070%3B%20%7D%20%0Acode%20%3E%20span%2Ebn%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Efl%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Ech%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Est%20%7B%20color%3A%20%23d14%3B%20%7D%20%0Acode%20%3E%20span%2Eco%20%7B%20color%3A%20%23888888%3B%20font%2Dstyle%3A%20italic%3B%20%7D%20%0Acode%20%3E%20span%2Eot%20%7B%20color%3A%20%23007020%3B%20%7D%20%0Acode%20%3E%20span%2Eal%20%7B%20color%3A%20%23ff0000%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%0Acode%20%3E%20span%2Efu%20%7B%20color%3A%20%23900%3B%20font%2Dweight%3A%20bold%3B%20%7D%20%20code%20%3E%20span%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%20%0A" rel="stylesheet" type="text/css" />

</head>

<body>




<h1 class="title toc-ignore">Survey design: power, precision and sample size</h1>
<h4 class="date"><em>29 April 2017</em></h4>



<p>This vignette covers the use of functions <code>incpower</code> and <code>incprecision</code>.</p>
<div id="function-incpower" class="section level2">
<h2>Function <code>incpower</code></h2>
<p>For this related set of calculations, we use the term “power” to mean the probability of obtaining a “statistically significant” result, <em>of the correct sign</em> in the estimation of an incidence difference, given some assumptions on effect size, recency test properties, and sample specification. See the vignette “introduction”, especially the glossary, for some crucial details.</p>
<p>Function <code>incpower</code> primarily calculates samples sizes required to achieve desired power, or the power available at specified sample size(s). This requires study context defining parameter values–such as hypothetical incidence rates, prevalences, coverage rates, design effects, and the assay characteristics known as <em>mean duration of recent infection</em> (MDRI) and <em>false recent rate</em> (FRR)–and returns .</p>
<p>A number of supplementary outputs are also supplied, such as</p>
<ul>
<li>demonstrative relative standard errors and confidence limits, in the case that point estimates attain the true/expected values.<br />
</li>
<li>expected survey counts, assuming a non structured sampling frame.</li>
</ul>
<div id="examples" class="section level3">
<h3>Examples</h3>
<p>Consider calculating the power to infer the correct ordering of an incidence of 5% and one of 3%, at a shared prevalences of 20%, given a single set of recency test property estimates i.e. one value for each of MDRI, the RSE of MDRI, FRR, the RSE of FRR, and time cutoff T namely, in order: 200 days, 5%, 1%, 20%, and 730 days. Assume complete coverage of recency status ascertainment, and no survey design effects. Finally, envision a common study sample size of 5000 persons and set <span class="math inline">\(\alpha\)</span> to 5%. That power, as opposed to sample size (the default) is the desired output, is captured in the specification of the argument <code>Power = &quot;out&quot;</code> and <code>SS = NULL</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">incpower</span>(<span class="dt">I1 =</span> <span class="fl">0.05</span>, <span class="dt">I2 =</span> <span class="fl">0.03</span>, <span class="dt">PrevH1 =</span> <span class="fl">0.20</span>, <span class="dt">PrevH2 =</span> <span class="fl">0.20</span>, <span class="dt">n1 =</span> <span class="dv">5000</span>,
        <span class="dt">n2 =</span> <span class="dv">5000</span>, <span class="dt">alpha =</span> <span class="fl">0.05</span>,<span class="dt">Power =</span> <span class="st">&quot;out&quot;</span>, <span class="dt">SS =</span> <span class="ot">NULL</span>, <span class="dt">CR =</span> <span class="dv">1</span>, <span class="dt">DE_H =</span> <span class="dv">1</span>,
        <span class="dt">DE_R =</span> <span class="dv">1</span>, <span class="dt">BMest =</span> <span class="st">&quot;same.test&quot;</span>, <span class="dt">MDRI =</span> <span class="dv">200</span>, <span class="dt">RSE_MDRI =</span> <span class="fl">0.05</span>, <span class="dt">FRR =</span> <span class="fl">0.01</span>,
        <span class="dt">RSE_FRR =</span> <span class="fl">0.20</span>, <span class="dt">BigT =</span> <span class="dv">730</span>)</code></pre></div>
<pre><code>## $Inc.Difference.Statistics
##   deltaI_Est RSE_deltaI RSE_deltaI.infSS Power Power.infSS CI.low  CI.up
## 1       0.02       0.33            0.052 0.858       &gt;0.99 0.0071 0.0329
## 
## $Implied.Incidence.Statistics
##   Survey Given.I RSE_I CI.low CI.up
## 1      1    0.05 0.115  0.039 0.061
## 2      2    0.03 0.147  0.021 0.039
## 
## $Implied.MDRI.Statistics
##   Given.MDRI CI.low CI.up
## 1        200  180.4 219.6
## 
## $Implied.FRR.Statistics
##   Given.FRR CI.low CI.up
## 1      0.01  0.006 0.014
## 
## $Implied.Subject.Counts
##                            Survey.1 Survey.2
## HIV.negative                   4000     4000
## HIV.positive                   1000     1000
## HIV.post.tested.for.recent     1000     1000
## Recency.test.pos                116       73</code></pre>
<p>Here the output returns that the power of this particular test is 0.858. In the limit of infinite sample size power approaches one.</p>
<p>For the benefit of survey planning (such as costing) the returned <code>Implied.Subject.Counts</code> object captures demonstrative survey counts in the case that expectation values are precisely attained.</p>
<p>To calculate the required (common) sample size for two surveys, to obtain a desired power:</p>
<ul>
<li>omit <code>n1</code> and <code>n2</code> or set both to <code>&quot;both&quot;</code></li>
<li>set <code>SS = &quot;out&quot;</code></li>
<li>set <code>Power</code> to the desired value.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">incpower</span>(<span class="dt">I1 =</span> <span class="fl">0.05</span>, <span class="dt">I2 =</span> <span class="fl">0.03</span>, <span class="dt">PrevH1 =</span> <span class="fl">0.20</span>, <span class="dt">PrevH2 =</span> <span class="fl">0.15</span>, <span class="dt">alpha =</span> <span class="fl">0.05</span>,
        <span class="dt">Power =</span> <span class="fl">0.8</span>, <span class="dt">SS =</span> <span class="st">&quot;out&quot;</span>, <span class="dt">CR =</span> <span class="dv">1</span>, <span class="dt">DE_H =</span> <span class="dv">1</span>, <span class="dt">DE_R =</span> <span class="dv">1</span>,
        <span class="dt">BMest =</span> <span class="st">&quot;FRR.indep&quot;</span>, <span class="dt">MDRI =</span> <span class="dv">200</span>, <span class="dt">RSE_MDRI =</span> <span class="fl">0.05</span>, <span class="dt">FRR =</span> <span class="kw">c</span>(<span class="fl">0.01</span>,<span class="fl">0.009</span>),
        <span class="dt">RSE_FRR =</span> <span class="kw">c</span>(<span class="fl">0.20</span>,<span class="fl">0.22</span>), <span class="dt">BigT =</span> <span class="dv">730</span>)</code></pre></div>
<pre><code>## $Minimum.Common.SS
## [1] 4122
## 
## $Inc.Difference.Statistics
##   deltaI_Est RSE_deltaI RSE_deltaI.infSS Power Power.infSS CI.low CI.up
## 1       0.02      0.357            0.063   0.8       &gt;0.99  0.006 0.034
## 
## $Implied.Incidence.Statistics
##   Survey Given.I RSE_I CI.low CI.up
## 1      1    0.05 0.124  0.038 0.062
## 2      2    0.03 0.150  0.021 0.039
## 
## $Implied.MDRI.Statistics
##   Given.MDRI CI.low CI.up
## 1        200  180.4 219.6
## 
## $Implied.FRR.Statistics
##   Given.FRR CI.low  CI.up
## 1     0.010 0.0061 0.0139
## 2     0.009 0.0051 0.0129
## 
## $Implied.Subject.Counts
##                            Survey.1 Survey.2
## HIV.negative                   3298     3504
## HIV.positive                    824      618
## HIV.post.tested.for.recent      824      618
## Recency.test.pos                 95       61</code></pre>
<p>The function call outputs that the necessary common study sample size is 4122 persons per study to achieve the desired 80% power given the specified population parameters and assay characteristics.</p>
</div>
</div>
<div id="function-incprecision" class="section level2">
<h2>Function <code>incprecision</code></h2>
<p>This function summarizes performance of a recent infection test into a standard error of the incidence estimate, given the estimated test properties and hypothetical survey context or the sample size necessary for a given level of precision.</p>
<div id="examples-1" class="section level3">
<h3>Examples</h3>
<p>The function invocation below returns the necessary sample size to have RSE of the incidence estimator equal to 25%, given a hypothetical prevalence, coverage rate, and recency test parameter estimates. Note that <code>n = &quot;out&quot;</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">incprecision</span>(<span class="dt">I =</span> <span class="fl">0.015</span>, <span class="dt">RSE_I =</span> <span class="fl">0.25</span>, <span class="dt">PrevH =</span> <span class="fl">0.2</span>, <span class="dt">CR =</span> <span class="dv">1</span>, <span class="dt">MDRI =</span> <span class="dv">200</span>,
            <span class="dt">RSE_MDRI =</span> <span class="fl">0.05</span>, <span class="dt">FRR =</span> <span class="fl">0.01</span>, <span class="dt">RSE_FRR =</span> <span class="fl">0.2</span>, <span class="dt">BigT =</span> <span class="dv">730</span>,
            <span class="dt">DE_H =</span> <span class="fl">1.1</span>, <span class="dt">DE_R =</span> <span class="fl">1.1</span>, <span class="dt">n =</span> <span class="st">'out'</span>)</code></pre></div>
<pre><code>## $sample.size
## [1] 3985
## 
## $Prev.HIV.and.recent
## [1] 0.00833
## 
## $Prev.HIV.and.nonrecent
## [1] 0.19167
## 
## $RSE.I.inf.sample
## [1] 0.07606
## 
## $RSE.PrevH
## [1] 0.03323
## 
## $RSE.PrevR
## [1] 0.03564</code></pre>
<p>Up to two arguments can be specified as ranges, with the input parameter <code>step</code> specifying the number of increments between the endpoints of the two ranges that are supplied under the argument name. Consider the calculation of sample size requirements for prevalence and incidence varied from 10 to 20% and 1.5 to 2% respectively:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">incprecision</span>(<span class="dt">I =</span> <span class="kw">c</span>(<span class="fl">0.015</span>,<span class="fl">0.02</span>), <span class="dt">RSE_I =</span> <span class="fl">0.25</span>, <span class="dt">PrevH =</span> <span class="kw">c</span>(<span class="fl">0.10</span>,<span class="fl">0.20</span>), <span class="dt">CR =</span> <span class="dv">1</span>,
             <span class="dt">MDRI =</span> <span class="dv">200</span>, <span class="dt">RSE_MDRI =</span> <span class="fl">0.05</span>, <span class="dt">FRR =</span> <span class="fl">0.01</span>, <span class="dt">RSE_FRR =</span> <span class="fl">0.2</span>, <span class="dt">BigT =</span> <span class="dv">700</span>,
             <span class="dt">DE_H =</span> <span class="dv">1</span>, <span class="dt">DE_R =</span> <span class="dv">1</span>, <span class="dt">n =</span> <span class="st">'out'</span>, <span class="dt">step =</span> <span class="dv">3</span>)</code></pre></div>
<pre><code>## $sample.size
##            PrevH = 0.1 PrevH = 0.15 PrevH = 0.2
## I = 0.015         2660         2660        2660
## I = 0.0175        2547         2547        2547
## I = 0.02          2489         2489        2489
## 
## $Prev.HIV.and.recent
##            PrevH = 0.1 PrevH = 0.15 PrevH = 0.2
## I = 0.015      0.00813      0.00813     0.00813
## I = 0.0175     0.00936      0.00936     0.00936
## I = 0.02       0.01045      0.01045     0.01045
## 
## $Prev.HIV.and.nonrecent
##            PrevH = 0.1 PrevH = 0.15 PrevH = 0.2
## I = 0.015      0.09187      0.09187     0.09187
## I = 0.0175     0.14064      0.14064     0.14064
## I = 0.02       0.18955      0.18955     0.18955
## 
## $RSE.I.inf.sample
##            PrevH = 0.1 PrevH = 0.15 PrevH = 0.2
## I = 0.015      0.05583      0.05583     0.05583
## I = 0.0175     0.06033      0.06033     0.06033
## I = 0.02       0.06549      0.06549     0.06549
## 
## $RSE.PrevH
##            PrevH = 0.1 PrevH = 0.15 PrevH = 0.2
## I = 0.015      0.05817      0.05817     0.05817
## I = 0.0175     0.04717      0.04717     0.04717
## I = 0.02       0.04009      0.04009     0.04009
## 
## $RSE.PrevR
##            PrevH = 0.1 PrevH = 0.15 PrevH = 0.2
## I = 0.015      0.02061      0.02061     0.02061
## I = 0.0175     0.02975      0.02975     0.02975
## I = 0.02       0.03817      0.03817     0.03817</code></pre>
<p>To calculate the RSE of incidence over a range of 5 values of prevalence of positivity, at a sample size of 5000:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">incprecision</span>(<span class="dt">I =</span> <span class="fl">0.017</span>, <span class="dt">RSE_I =</span> <span class="st">'out'</span>, <span class="dt">PrevH =</span> <span class="kw">c</span>(<span class="fl">0.10</span>,<span class="fl">0.20</span>), <span class="dt">CR =</span> <span class="dv">1</span>, <span class="dt">MDRI =</span> <span class="dv">211</span>,
             <span class="dt">RSE_MDRI =</span> <span class="fl">0.05</span>, <span class="dt">FRR =</span> <span class="fl">0.009</span>, <span class="dt">RSE_FRR =</span> <span class="fl">0.2</span>, <span class="dt">BigT =</span> <span class="dv">720</span>, <span class="dt">n =</span> <span class="dv">5000</span>,
             <span class="dt">step =</span> <span class="dv">5</span>)</code></pre></div>
<pre><code>## $RSE_I
##           PrevH   RSE_I
## 1   PrevH = 0.1 0.16868
## 2 PrevH = 0.125 0.17352
## 3  PrevH = 0.15 0.17885
## 4 PrevH = 0.175 0.18470
## 5   PrevH = 0.2 0.19112
## 
## $Prev.HIV.and.recent
##           PrevH Prev.HIV.and.recent
## 1   PrevH = 0.1             0.00947
## 2 PrevH = 0.125             0.00945
## 3  PrevH = 0.15             0.00944
## 4 PrevH = 0.175             0.00943
## 5   PrevH = 0.2             0.00942
## 
## $Prev.HIV.and.nonrecent
##           PrevH Prev.HIV.and.nonrecent
## 1   PrevH = 0.1                0.09053
## 2 PrevH = 0.125                0.11555
## 3  PrevH = 0.15                0.14056
## 4 PrevH = 0.175                0.16557
## 5   PrevH = 0.2                0.19058
## 
## $RSE.I.inf.sample
##           PrevH RSE.I.inf.sample
## 1   PrevH = 0.1          0.05363
## 2 PrevH = 0.125          0.05557
## 3  PrevH = 0.15          0.05824
## 4 PrevH = 0.175          0.06166
## 5   PrevH = 0.2          0.06585
## 
## $RSE.PrevH
##           PrevH RSE.PrevH
## 1   PrevH = 0.1   0.04243
## 2 PrevH = 0.125   0.03742
## 3  PrevH = 0.15   0.03367
## 4 PrevH = 0.175   0.03071
## 5   PrevH = 0.2   0.02828
## 
## $RSE.PrevR
##           PrevH RSE.PrevR
## 1   PrevH = 0.1   0.01383
## 2 PrevH = 0.125   0.01748
## 3  PrevH = 0.15   0.02113
## 4 PrevH = 0.175   0.02479
## 5   PrevH = 0.2   0.02845</code></pre>
</div>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
